### ISSUE TITLE
Error on confirmation page

### ISSUE THREAD

**Issue by Drillyus** [bestmomo/laravel-email-confirmation#13]
HI,
  When i click on the confirmation link on my email, i get this ;

  Url : http://localhost/laravel/back-office/public/confirmation/2/c9rFW8781eXQQQjTlNuv6dUnbbb2QA
  ( my home is http://localhost/laravel/back-office/public )

result : 
Fatal error: Uncaught ReflectionException: Class config does not exist in /opt/lampp/htdocs/laravel/back-office/vendor/laravel/framework/src/Illuminate/Container/Container.php:752 Stack trace: #0 /opt/lampp/htdocs/laravel/back-office/vendor/laravel/framework/src/Illuminate/Container/Container.php(752): ReflectionClass->__construct('config') #1 /opt/lampp/htdocs/laravel/back-office/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('config') #2 /opt/lampp/htdocs/laravel/back-office/vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\Container\Container->resolve('config', Array) #3 /opt/lampp/htdocs/laravel/back-office/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(732): Illuminate\Container\Container->make('config', Array) #4 /opt/lampp/htdocs/laravel/back-office/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(110): Illuminate\Foundation\Application->make('config', Array) #5 /opt/lampp/htdocs/laravel/bac in /opt/lampp/htdocs/laravel/back-office/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 752

why?

**Comment by Drillyus** [comment]
Ok it was due ton space in .env on MAIL_FROM_NAME param.
